server:
  port: 8080
  servlet:
    context-path: /
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
      #前端页面传Date值时格式化
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  rabbitmq:
    port: 5672
    host: 192.168.194.132
    username: admin
    password: 614
    virtual-host: /
    connection-timeout: 15s
    #启用消息确认机制。能收到MQ Broker的异步响应
    publisher-confirms: true







