
#设置服务器端口号
server:
  port: 8080

#security配置
spring:
  jackson:
    serialization:
      indent_output: true


demo:
  security:
    header: Authorization #请求头部属性名
    signing_key: pyb068@gmail.com #JWT 签名秘钥
    token_expiration: 108000000 #token失效时间 30*60*60*1000
    route:
      auth_path: /tk/auth
      refresh_path: /tk/refresh
    ignore:
      get:
        - /test/**
        - /ignore/testget
      post:
        - /ignore/testpost