server:
  port: 8080
eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka server
    fetch-registry: true  #是否从 Eureka sever 获取注册信息
    service-url:
        defaultZone: http://localhost:8080/eureka/
