spring:
  application:
    name: sc-demo-alibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.14:8848 #注册进 nacos

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"