server:
  port: 8060

spring:
  application:
    name: sc-demo-microservice-zuul #这个名字会注册到 Eureka 里去

#Actuato 配置
management:
  endpoint:
# 暴露shutdown功能
#    shutdown:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'  #暴露哪些端点
        exclude:      #隐藏哪些端点

#Eureka client端配置
eureka:
  client:
    service-url:
        defaultZone: http://user:614@localhost:8080/eureka/,http://user:614@localhost:8081/eureka/
  instance:
    prefer-ip-address: true #将自己ip注册到Eureka Server

zuul:
  ribbon-isolation-strategy: thread #hystrix隔离策略改为线程 (默认是信号量
  thread-pool:
      use-separate-thread-pools: true #让每个路由使用它独立的线程池
      thread-pool-key-prefix: myprefix- #前缀
  routes: #路由配置
    local-router:
      url: local/test #本地转发
      path: forward:/local/test
    aggregate-router:
      url: aggregate/**
      path: forward:/aggregate/**
    user-router:
      sensitive-headers: Cookie,Set-Cookie,Authorization  #指定敏感header
      service-id: sc-demo-microservice-user
      path: /zuul_user/**
    movie-router:
      service-id: sc-demo-microservice-movie
      path: /zuul_movie/**
  #  ignored-services 指定微服务忽略它，不对它进行路由,使用"*" 忽略所有,只路由指定了的
  ignored-services: sc-demo-microservice-eureka_1,sc-demo-microservice-eureka_2